main/urls.py
from django.urls import path
from main.views import show_main
from main.views import show_main, create_product, show_xml, show_json, show_xml_by_id, show_json_by_id
from main.views import register, login_user, logout_user, edit_product, delete_product, add_product_entry_ajax, create_product_flutter

app_name = 'main'

urlpatterns = [
    path('', show_main, name='show_main'),
    path('create-product', create_product, name='create_product'),
    path('xml/', show_xml, name='show_xml'),
    path('json/', show_json, name='show_json'),
    path('xml/<str:id>/', show_xml_by_id, name='show_xml_by_id'),
    path('json/<str:id>/', show_json_by_id, name='show_json_by_id'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('edit-product/<uuid:id>', edit_product, name='edit_product'),
    path('delete/<uuid:id>', delete_product, name='delete_product'),
    path('create-ajax', add_product_entry_ajax, name='add_product_entry_ajax'),
    path('create-flutter/', create_product_flutter, name='create_mood_flutter'),
]

tioutfitters/urls.py
from django.contrib import admin
from django.urls import path

from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('auth/', include('authentication.urls')), 
]

main/models.py
from django.db import models
import uuid
from django.contrib.auth.models import User

# Create your models here.
class Product(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)  # tambahkan baris ini
    name = models.CharField(max_length=255)
    price = models.IntegerField()
    description = models.TextField()
    # favorite = models.BooleanField()

main/forms.py
from django.forms import ModelForm
from main.models import Product
from django.utils.html import strip_tags

class ProductForm(ModelForm):
    class Meta:
        model = Product
        fields = ["name", "price", "description", 
                #   "favorite"
                  ]

    def clean_product_name(self):
        product_name = self.cleaned_data["name"]
        return strip_tags(product_name)

    def clean_description(self):
        description = self.cleaned_data["description"]
        return strip_tags(description)

main/views.py
import datetime
from django.urls import reverse
from django.shortcuts import render, redirect, reverse
from main.forms import ProductForm
from main.models import Product
from django.http import HttpResponse, HttpResponseRedirect
from django.core import serializers
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_POST
from django.utils.html import strip_tags
import json
from django.http import JsonResponse

# Create your views here.
@login_required(login_url='/login')
def show_main(request):
    context = {
        'username': request.user.username,
        'npm' : '2306221056',
        'name': 'Aliefa Alsyafiandra Setiawati Mahdi',
        'class': 'PBP F',
        'last_login': request.COOKIES['last_login'],
    }

    return render(request, "main.html", context)

def create_product(request):
    form = ProductForm(request.POST or None)

    if form.is_valid() and request.method == "POST":
        product_entry = form.save(commit=False)
        product_entry.user = request.user
        product_entry.save()
        return redirect('main:show_main')

    context = {'form': form}
    return render(request, "create_product.html", context)

def show_xml(request):
    data = Product.objects.filter(user=request.user)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json(request):
    data = Product.objects.filter(user=request.user)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_xml_by_id(request, id):
    data = Product.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json_by_id(request, id):
    data = Product.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your account has been successfully created!')
            return redirect('main:login')
    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request):
   if request.method == 'POST':
      form = AuthenticationForm(data=request.POST)

      if form.is_valid():
            user = form.get_user()
            login(request, user)
            response = HttpResponseRedirect(reverse("main:show_main"))
            response.set_cookie('last_login', str(datetime.datetime.now()))
            return response
      else:
            messages.error(request, "Invalid username or password. Please try again.")

   else:
      form = AuthenticationForm(request)
   context = {'form': form}
   return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('main:login'))
    response.delete_cookie('last_login')
    return response

def edit_product(request, id):
    # Get product entry berdasarkan id
    product = Product.objects.get(pk = id)

    # Set product entry sebagai instance dari form
    form = ProductForm(request.POST or None, instance=product)

    if form.is_valid() and request.method == "POST":
        # Simpan form dan kembali ke halaman awal
        form.save()
        return HttpResponseRedirect(reverse('main:show_main'))

    context = {'form': form}
    return render(request, "edit_product.html", context)

def delete_product(request, id):
    # Get product berdasarkan id
    product = Product.objects.get(pk = id)
    # Hapus product
    product.delete()
    # Kembali ke halaman awal
    return HttpResponseRedirect(reverse('main:show_main'))

@csrf_exempt
@require_POST
def add_product_entry_ajax(request):
    product_name = strip_tags(request.POST.get("name"))
    description = strip_tags(request.POST.get("description")) 
    price = request.POST.get("price")
    # favorite = request.POST.get("favorite")
    user = request.user

    new_product = Product(
        name=product_name, price=price,
        description=description, 
        # favorite=favorite,
        user=user
    )
    new_product.save()

    return HttpResponse(b"CREATED", status=201)

@csrf_exempt
def create_product_flutter(request):
    if request.method == 'POST':

        data = json.loads(request.body)
        new_product = Product.objects.create(
            user=request.user,
            name=data["name"],
            price=int(data["price"]),
            description=data["description"]
        )

        new_product.save()

        return JsonResponse({"status": "success"}, status=200)
    else:
        return JsonResponse({"status": "error"}, status=401)

main/templates/card_product.html
<div class="relative break-inside-avoid">
  <div class="relative top-5 bg-neutral-100 mb-6 break-inside-avoid flex flex-col transform hover:scale-110 transition-transform duration-300">
    <div class="bg-neutral-200 text-gray-800 p-4">
      <h3 class="font-bold text-xl mb-2 mr-20 pr-20">{{product_entry.name}}</h3>
      <p class="text-gray-600">${{product_entry.price}}</p>
    </div>
    <div class="p-4">
      <p class="text-gray-700 mb-2">
        <span class="bg-[linear-gradient(to_bottom,transparent_0%,transparent_calc(100%_-_1px))] bg-[length:100%_1.5rem] pb-1">{{product_entry.description}}</span>
      </p>
      <div class="mt-4">
        <div class="relative pt-1">
          <div class="flex mb-2 items-center justify-between">
          </div>
        </div>
      </div>
    </div>
    <div class="items-center absolute top-0 right-4 flex space-x-1">
      {% if product_entry.favorite %}
        <img src="https://i.kym-cdn.com/entries/icons/facebook/000/037/690/cover4.jpg" class="m-1 h-10 w-10" viewBox="0 0 20 20" fill="currentColor">
        </img>
      {% else %}
        <img src="https://i.pinimg.com/564x/79/9b/3b/799b3b899bbccd41ac9cef7a6caba3e9.jpg" class="m-1 h-10 w-10" viewBox="0 0 20 20" fill="currentColor">
        </img>
      {% endif %}
      <a href="{% url 'main:edit_product' product_entry.pk %}" class="m-2 bg-amber-200 hover:bg-amber-300 hover:scale-110 p-2 transition duration-300">
        <img src="https://www.pngplay.com/wp-content/uploads/4/Pencil-Transparent-Free-PNG.png" class="h-9 w-9" viewBox="0 0 20 20" fill="currentColor">
        </img>
      </a>
      <a href="{% url 'main:delete_product' product_entry.pk %}" class="m-2 bg-red-200 hover:bg-red-500 hover:scale-110 p-2 transition duration-300">
        <img src="https://www.pngplay.com/wp-content/uploads/2/Outdoor-Trash-Can-Transparent-PNG.png" class="h-9 w-9" viewBox="0 0 20 20" fill="currentColor">
      </img>
      </a>
    </div>
  </div>
</div>

main/templates/create_product.html
{% extends 'base.html' %}

{% block meta %}
<title>Add Product</title>
{% endblock meta %}

{% block content %}
<div class="font-mono min-h-screen flex items-center justify-center w-screen bg-auto bg-repeat py-12 px-4 sm:px-6 lg:px-8" style="background-image: url(https://img.freepik.com/premium-photo/seamless-leopard-print-pattern-high-resolution-digital-art-illustration_349618-39995.jpg)">
  <div class="mx-20 bg-neutral-950 w-full space-y-8">
    <h2 class="mt-6 text-center text-white text-3xl font-extrabold">
      Add Product
    </h2>
    <div class="bg-neutral-300 p-6 form-style">
      <form method="POST" class="space-y-6">
        {% csrf_token %}
        {% for field in form %}
          <div class="flex flex-col">
            <label for="{{ field.id_for_label }}" class="mb-2 font-semibold text-gray-700">
              {{ field.label }}
            </label>
            <div class="w-full">
              {{ field }}
            </div>
            {% if field.help_text %}
              <p class="mt-1 text-sm text-gray-500">{{ field.help_text }}</p>
            {% endif %}
            {% for error in field.errors %}
              <p class="mt-1 text-sm text-red-600">{{ error }}</p>
            {% endfor %}
          </div>
        {% endfor %}
      <div>
        <button type="submit" class="group relative w-full flex justify-center py-2 px-4 border border-transparent text-sm font-bold rounded-md text-white bg-blue-700 hover:bg-pink-500 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-pink-500">
          Add Product
        </button>
      </div>
    </form>

    {% if messages %}
    <div class="mt-4">
      {% for message in messages %}
      {% if message.tags == "success" %}
            <div class="bg-green-100 border border-green-400 text-green-700 px-4 py-3 rounded relative" role="alert">
                <span class="block sm:inline">{{ message }}</span>
            </div>
        {% elif message.tags == "error" %}
            <div class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative" role="alert">
                <span class="block sm:inline">{{ message }}</span>
            </div>
        {% else %}
            <div class="bg-blue-100 border border-blue-400 text-blue-700 px-4 py-3 rounded relative" role="alert">
                <span class="block sm:inline">{{ message }}</span>
            </div>
        {% endif %}
      {% endfor %}
    </div>
    {% endif %}

  </div>
</div>
{% endblock content %}

main/templates/edit_product.html
{% extends 'base.html' %}
{% load static %}
{% block meta %}
<title>Edit Product</title>
{% endblock meta %}

{% block content %}
{% include 'navbar.html' %}
<div class="font-mono min-h-screen flex items-center justify-center w-screen bg-auto bg-repeat py-12 px-4 sm:px-6 lg:px-8" style="background-image: url(https://img.freepik.com/premium-photo/seamless-leopard-print-pattern-high-resolution-digital-art-illustration_349618-39995.jpg)">
  <div class="mx-20 mt-16 bg-neutral-950 w-full space-y-8">
    <h2 class="mt-6 text-center text-white text-3xl font-extrabold">
      Edit Product
    </h2>
    <div class="bg-neutral-300 p-6 form-style">
      <form method="POST" class="space-y-6">
          {% csrf_token %}
          {% for field in form %}
              <div class="flex flex-col">
                  <label for="{{ field.id_for_label }}" class="mb-2 font-semibold text-gray-700">
                      {{ field.label }}
                  </label>
                  <div class="w-full">
                      {{ field }}
                  </div>
                  {% if field.help_text %}
                      <p class="mt-1 text-sm text-gray-500">{{ field.help_text }}</p>
                  {% endif %}
                  {% for error in field.errors %}
                      <p class="mt-1 text-sm text-red-600">{{ error }}</p>
                  {% endfor %}
              </div>
          {% endfor %}
          <div class="flex justify-center mt-6">
              <button type="submit" class="bg-blue-700 text-white font-semibold px-6 py-3 rounded-lg hover:bg-pink-500 transition duration-300 ease-in-out w-full">
                  Edit Product
              </button>
          </div>
      </form>
  </div>
  </div>
</div>
{% endblock %}

main/templates/login.html
{% extends 'base.html' %}

{% block meta %}
<title>Login</title>
{% endblock meta %}

{% block content %}
<div class="font-mono min-h-screen flex items-center justify-center w-screen bg-auto bg-repeat py-12 px-4 sm:px-6 lg:px-8" style="background-image: url(https://img.freepik.com/premium-photo/seamless-leopard-print-pattern-high-resolution-digital-art-illustration_349618-39995.jpg)">
  <div class="mx-20 bg-neutral-950 w-full space-y-8 rounded-3xl">
    <h2 class="mt-6 text-center text-white text-3xl font-extrabold">
      Login
    </h2>
    <form class="px-20 mt-8 space-y-6" method="POST" action="">
      {% csrf_token %}
      <input type="hidden" name="remember" value="true">
      <div class="rounded-md shadow-sm -space-y-px">
        <div>
          <label for="username" class="sr-only">Username</label>
          <input id="username" name="username" type="text" required="" placeholder="Username" class="appearance-none rounded-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-t-md focus:outline-none focus:ring-blue-700 focus:border-blue-700 focus:z-10 sm:text-sm">
        </div>
        <div>
          <label for="password" class="sr-only">Password</label>
          <input id="password" name="password" type="password" required="" placeholder="Password" class="appearance-none rounded-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-b-md focus:outline-none focus:ring-blue-700 focus:border-blue-700 focus:z-10 sm:text-sm">
        </div>
      </div>

      <div>
        <button type="submit" class="group relative w-full flex justify-center py-2 px-4 border border-transparent text-sm font-bold rounded-md text-white bg-blue-700 hover:bg-pink-500 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-700">
          Sign in
        </button>
      </div>
    </form>

    {% if messages %}
    <div class="mt-4">
      {% for message in messages %}
      {% if message.tags == "success" %}
            <div class="bg-green-100 border border-green-400 text-green-700 px-4 py-3 rounded relative" role="alert">
                <span class="block sm:inline">{{ message }}</span>
            </div>
        {% elif message.tags == "error" %}
            <div class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative" role="alert">
                <span class="block sm:inline">{{ message }}</span>
            </div>
        {% else %}
            <div class="bg-blue-100 border border-blue-400 text-blue-700 px-4 py-3 rounded relative" role="alert">
                <span class="block sm:inline">{{ message }}</span>
            </div>
        {% endif %}
      {% endfor %}
    </div>
    {% endif %}

    <div class="text-center pb-6">
      <p class="text-sm text-white">
        Don't have an account yet?
        <a href="{% url 'main:register' %}" class="font-medium text-blue-200 hover:text-blue-300">
          Register Now
        </a>
      </p>
    </div>
  </div>
</div>
{% endblock content %}

main/templates/main.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>TIOutfitters</title>
<script src="https://cdn.jsdelivr.net/npm/dompurify@3.1.7/dist/purify.min.js"></script>
{% endblock meta %}
{% block content %}
{% include 'navbar.html' %}
<div class="font-mono pt-20 w-screen bg-neutral-950 p-4">
    <h1 class="text-white font-bold sm:text-2xl text-left">
        Welcome, {{ username }}!
    </h1>
</div>
<div class="overflow-x-hidden font-mono px-4 md:px-8 pb-8 pt-30 min-h-screen bg-repeat flex flex-col" style="background-image: url(https://img.freepik.com/premium-photo/seamless-leopard-print-pattern-high-resolution-digital-art-illustration_349618-39995.jpg);">
    <div class="p-3">
        <div class="flex items-center bg-neutral-300 py-2 px-4 w-fit">
          <h1 class="text-black text-center">Last Login: {{last_login}}</h1>
        </div>
        <div class="flex justify-end mb-6">
            <a href="{% url 'main:create_product' %}" class="bg-blue-600 hover:bg-blue-700 text-white font-bold py-2 px-4 mx-2 transition duration-300 ease-in-out transform hover:scale-105">
                Add New Product
            </a>
            <button data-modal-target="crudModal" data-modal-toggle="crudModal" class="btn bg-blue-600 hover:bg-blue-700 text-white font-bold py-2 px-4 transition duration-300 ease-in-out transform hover:scale-105" onclick="showModal();">
                Add New Product Entry by AJAX
              </button>
        </div>
    </div>        
    
    <div id="product_entry_cards"></div>
    <div id="crudModal" tabindex="-1" aria-hidden="true" class="hidden fixed inset-0 z-50 w-full flex items-center justify-center bg-gray-800 bg-opacity-50 overflow-x-hidden overflow-y-auto transition-opacity duration-300 ease-out">
        <div id="crudModalContent" class="relative bg-white rounded-lg shadow-lg w-5/6 sm:w-3/4 md:w-1/2 lg:w-1/3 mx-4 sm:mx-0 transform scale-95 opacity-0 transition-transform transition-opacity duration-300 ease-out">
            <!-- Modal header -->
            <div class="flex items-center justify-between p-4 border-b rounded-t">
                <h3 class="text-xl font-semibold text-gray-900">
                Add New Product Entry
                </h3>
                <button type="button" class="text-gray-400 bg-transparent hover:bg-gray-200 hover:text-gray-900 rounded-lg text-sm p-1.5 ml-auto inline-flex items-center" id="closeModalBtn">
                <svg aria-hidden="true" class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
                    <path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd"></path>
                </svg>
                <span class="sr-only">Close modal</span>
                </button>
            </div>
            <!-- Modal body -->
            <div class="px-6 py-4 space-y-6 form-style">
                <form id="productEntryForm">
                <div class="mb-4">
                    <label for="product_name" class="block text-sm font-medium text-gray-700">Name</label>
                    <input type="text" id="product_name" name="name" class="mt-1 block w-full border border-gray-300 rounded-md p-2 hover:border-indigo-700" placeholder="Enter your product name" required>
                </div>
                <div class="mb-4">
                    <label for="price" class="block text-sm font-medium text-gray-700">Price</label>
                    <input type="number" id="price" name="price" min="0" class="mt-1 block w-full border border-gray-300 rounded-md p-2 hover:border-indigo-700" required>
                </div>
                <div class="mb-4">
                    <label for="description" class="block text-sm font-medium text-gray-700">Description</label>
                    <textarea id="description" name="description" rows="3" class="mt-1 block w-full h-52 resize-none border border-gray-300 rounded-md p-2 hover:border-indigo-700" placeholder="Describe your product" required></textarea>
                </div>
                </form>
            </div>
            <!-- Modal footer -->
            <div class="flex flex-col space-y-2 md:flex-row md:space-y-0 md:space-x-2 p-6 border-t border-gray-200 rounded-b justify-center md:justify-end">
                <button type="button" class="bg-gray-500 hover:bg-gray-600 text-white font-bold py-2 px-4 rounded-lg" id="cancelButton">Cancel</button>
                <button type="submit" id="submitProductEntry" form="productEntryForm" class="bg-indigo-700 hover:bg-indigo-600 text-white font-bold py-2 px-4 rounded-lg">Save</button>
            </div>
        </div>
    </div>
</div>

<div class="bg-blue-700 font-mono fixed bottom-0 left-0 w-screen">
    <p class="p-4 text-white">{{name}} - {{npm}} - {{class}}</p>
</div>
<script>
    function addProductEntry() {
        fetch("{% url 'main:add_product_entry_ajax' %}", {
            method: "POST",
            body: new FormData(document.querySelector('#productEntryForm')),
        })
        .then(response => refreshProductEntries())
        
        document.getElementById("productEntryForm").reset(); 
        document.querySelector("[data-modal-toggle='crudModal']").click();
        
        return false;
    }
    async function getProductEntries(){
        return fetch("{% url 'main:show_json' %}").then((res) => res.json())
    }
    async function refreshProductEntries() {
        document.getElementById("product_entry_cards").innerHTML = "";
        document.getElementById("product_entry_cards").className = "";
        const productEntries = await getProductEntries();
        let htmlString = "";
        let classNameString = "";

        if (productEntries.length === 0) {
            classNameString = "mx-auto bg-neutral-700 flex flex-col items-center justify-center p-6";
            htmlString = `
                <div class="mx-auto bg-neutral-700 flex flex-col items-center justify-center p-6">
                    <img src="{% static 'image/sedih-banget.png' %}" alt="Sad face" class="w-32 h-32 mb-4"/>
                    <p class="text-center text-white mt-4">No products yet!</p>
                </div>
                `;
        }
        else {
            classNameString = "columns-1 sm:columns-2 lg:columns-3 gap-6 space-y-6 w-full"
            productEntries.forEach((item) => {
                const product_name = DOMPurify.sanitize(item.fields.name);
                const description = DOMPurify.sanitize(item.fields.description);
                htmlString += `
                <div class="relative break-inside-avoid">
                    <div class="relative top-5 bg-neutral-100 mb-6 break-inside-avoid flex flex-col transform hover:scale-110 transition-transform duration-300">
                        <div class="bg-neutral-200 text-gray-800 p-4">
                        <h3 class="font-bold text-xl mb-2 mr-20 pr-20">${product_name}</h3>
                        <p class="text-gray-600">$${item.fields.price}</p>
                        </div>
                        <div class="p-4">
                        <p class="text-gray-700 mb-2">
                            <span class="bg-[linear-gradient(to_bottom,transparent_0%,transparent_calc(100%_-_1px))] bg-[length:100%_1.5rem] pb-1">${description}</span>
                        </p>
                        <div class="mt-4">
                            <div class="relative pt-1">
                            <div class="flex mb-2 items-center justify-between">
                            </div>
                            </div>
                        </div>
                        </div>
                        <div class="items-center absolute top-0 right-4 flex space-x-1">`
                        // if (item.fields.favorite) {
                        //     htmlString += `
                        //     <img src="https://i.kym-cdn.com/entries/icons/facebook/000/037/690/cover4.jpg" class="m-1 h-10 w-10" viewBox="0 0 20 20" fill="currentColor">
                        //     </img> `
                        // }
                        // else {
                        //     htmlString += `
                        //     <img src="https://i.pinimg.com/564x/79/9b/3b/799b3b899bbccd41ac9cef7a6caba3e9.jpg" class="m-1 h-10 w-10" viewBox="0 0 20 20" fill="currentColor">
                        //     </img>`
                        // }
                        htmlString += `
                        <a href="/edit-product/${item.pk}" class="m-2 bg-amber-200 hover:bg-amber-300 hover:scale-110 p-2 transition duration-300">
                            <img src="https://www.pngplay.com/wp-content/uploads/4/Pencil-Transparent-Free-PNG.png" class="h-9 w-9" viewBox="0 0 20 20" fill="currentColor">
                            </img>
                        </a>
                        <a href="/delete/${item.pk}" class="m-2 bg-red-200 hover:bg-red-500 hover:scale-110 p-2 transition duration-300">
                            <img src="https://www.pngplay.com/wp-content/uploads/2/Outdoor-Trash-Can-Transparent-PNG.png" class="h-9 w-9" viewBox="0 0 20 20" fill="currentColor">
                        </img>
                        </a>
                        </div>
                    </div>
                </div>
                `;
            });
        }
        document.getElementById("product_entry_cards").className = classNameString;
        document.getElementById("product_entry_cards").innerHTML = htmlString;
    }
    refreshProductEntries();

    const modal = document.getElementById('crudModal');
    const modalContent = document.getElementById('crudModalContent');

    function showModal() {
        const modal = document.getElementById('crudModal');
        const modalContent = document.getElementById('crudModalContent');

        modal.classList.remove('hidden'); 
        setTimeout(() => {
            modalContent.classList.remove('opacity-0', 'scale-95');
            modalContent.classList.add('opacity-100', 'scale-100');
        }, 50); 
    }

    function hideModal() {
        const modal = document.getElementById('crudModal');
        const modalContent = document.getElementById('crudModalContent');

        modalContent.classList.remove('opacity-100', 'scale-100');
        modalContent.classList.add('opacity-0', 'scale-95');

        setTimeout(() => {
            modal.classList.add('hidden');
        }, 150); 
    }

    document.getElementById("cancelButton").addEventListener("click", hideModal);
    document.getElementById("closeModalBtn").addEventListener("click", hideModal);

    document.getElementById("productEntryForm").addEventListener("submit", (e) => {
        e.preventDefault();
        addProductEntry();
    })
  </script>
{% endblock content %}

main/templates/register.html
{% extends 'base.html' %}

{% block meta %}
<title>Register</title>
{% endblock meta %}

{% block content %}
<div class="font-mono min-h-screen flex items-center justify-center w-screen bg-auto bg-repeat py-12 px-4 sm:px-6 lg:px-8" style="background-image: url(https://img.freepik.com/premium-photo/seamless-leopard-print-pattern-high-resolution-digital-art-illustration_349618-39995.jpg)">
  <div class="mx-20 bg-neutral-950 w-full space-y-8 rounded-3xl">
    <h2 class="mt-6 text-center text-white text-3xl font-extrabold">
      Create account
    </h2>
    <form class="px-20 mt-8 space-y-6" method="POST" action="">
      {% csrf_token %}
      <input type="hidden" name="remember" value="true">
      <div class="rounded-md space-y-px">
        {% for field in form %}
        <div class="{% if not forloop.first %}my-4{% endif %}">
          <label for="{{ field.id_for_label }}" class="my-2 font-semibold text-white">
            {{ field.label }}
          </label>
          <div class="relative">
            {{ field }}
            <div class="absolute inset-y-0 right-0 pr-3 flex items-center pointer-events-none">
              {% if field.errors %}
                <svg class="h-5 w-5 text-red-500" fill="currentColor" viewBox="0 0 20 20">
                  <path fill-rule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7 4a1 1 0 11-2 0 1 1 0 012 0zm-1-9a1 1 0 00-1 1v4a1 1 0 102 0V6a1 1 0 00-1-1z" clip-rule="evenodd" />
                </svg>
              {% endif %}
            </div>
          </div>
          {% if field.errors %}
            {% for error in field.errors %}
              <p class="mt-1 text-sm text-red-600">{{ error }}</p>
            {% endfor %}
          {% endif %}
        </div>
      {% endfor %}
    </div>

    <div>
      <button type="submit" class="group relative w-full flex justify-center py-2 px-4 border border-transparent text-sm font-bold rounded-md text-white bg-blue-700 hover:bg-pink-500 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-700">
        Register
      </button>
    </div>
  </form>

  {% if messages %}
  <div class="mt-4">
    {% for message in messages %}
    <div class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative" role="alert">
      <span class="block sm:inline">{{ message }}</span>
    </div>
    {% endfor %}
  </div>
  {% endif %}

  <div class="text-center pb-6">
    <p class="text-sm text-white">
      Already have an account?
      <a href="{% url 'main:login' %}" class="font-medium text-blue-200 hover:text-blue-300">
        Login here
      </a>
    </p>
  </div>
</div>
</div>
{% endblock content %}